package com.dada.guanli.dataobject;

public class PassWordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password_hou.id
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password_hou.password
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password_hou.user_hou_id
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    private Integer userHouId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password_hou.id
     *
     * @return the value of password_hou.id
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column password_hou.id
     *
     * @param id the value for password_hou.id
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password_hou.password
     *
     * @return the value of password_hou.password
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column password_hou.password
     *
     * @param password the value for password_hou.password
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password_hou.user_hou_id
     *
     * @return the value of password_hou.user_hou_id
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    public Integer getUserHouId() {
        return userHouId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column password_hou.user_hou_id
     *
     * @param userHouId the value for password_hou.user_hou_id
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    public void setUserHouId(Integer userHouId) {
        this.userHouId = userHouId;
    }
}