package com.dada.guanli.dao;

import com.dada.guanli.dataobject.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hou
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hou
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hou
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hou
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    UserDO selectByPrimaryKey(Integer id);
    UserDO selectByZhanghao(String zhanghao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hou
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hou
     *
     * @mbg.generated Sat Jun 01 23:15:48 CST 2019
     */
    int updateByPrimaryKey(UserDO record);


}